### PR TITLE
Fixes login path to support configured base path

### LINKED ISSUE #46: Login redirect does not honor base-path
I use kafkahq with security turned on and have the base-path set to "/kafka-hq".

When I browse to `/kafka-hq` I get redirected to `/login/unauthorized` instead of `/kafka-hq/login/unauthorized`. When using a reverse proxy the path `/login/unauthorized` will  not serve the kafkahq login page because the prefix is missing.

Even browsing to `/kafka-hq/login/unauthorized` will forward `/login/unauthorized`.

### PR DESCRIPTION
**Pull request by tine2k**
fixes #46

### CODE REVIEW

**Comment by tine2k** [comment]
I don't know what's wrong with the build. Tests run fine on my machine. Can you help @tchiotludo ?

**Comment by tchiotludo** [comment]
My Travis build is wrong on pull request, my fault.

Good fix I think, I will look if I missed other one and fix Travis 

Thanks 😉

**Comment by tine2k** [comment]
Thanks @tchiotludo, do you mind creating a new release?

**Comment by tchiotludo** [comment]
In the dev release they is also new bugfix like this one : #42 that was blocked by a micronaut issue micronaut-projects/micronaut-core#1532 that was just fix 1 hour ago.

I will look this evening if I could use a snapshot release to have this fix included before the release of the new version (I think they have a 3 weeks sprints)

**Comment by tchiotludo** [comment]
Release done without the fix, the snapshot release is not an option but it's better than now !  
Thanks

**Comment by tine2k** [comment]
Thanks a bunch!

**Pull request merged**
