### PR TITLE
Connect Multicluster #127

### PR DESCRIPTION
**Pull request by polarising-java**
#127 Connect Multicluster development.

Transform single connect to a list of connects.

### CODE REVIEW

**Comment by tchiotludo** [comment]
Great work !!! 
Works well, all is perfect ! 

Thanks a lot

**Comment by ankon** [comment]
How does this affect existing configurations?

**Comment by tchiotludo** [comment]
It only changed the configuration of connect to an array instead of object : 
https://github.com/tchiotludo/kafkahq/blob/c09be06d175104f4a3509d2a0566f7be781406d8/application.example.yml#L45-L65

**Comment by ankon** [comment]
Right. If I understand correctly then this would break existing configurations, which would need to be changed to an array of named things as well. Would be good to mention that in the release notes :)

**Comment by tchiotludo** [comment]
yes right, forgot to add it, just corrected thanks :)

**Comment by ankon** [comment]
Thanks. 

Btw, @tchiotludo did you see my other invitation/issue? :)

**Pull request merged**
