### PR TITLE
Make including the consumer group data optional

### PR DESCRIPTION
**Pull request by ankon**
One of the parts from #134 that could be useful on its own, see there for the full discussion.

### CODE REVIEW

**Comment by jorgheymans** [comment]
thanks @ankon , confirming this makes the topic list page usable again !

**Comment by tchiotludo** [comment]
thanks @ankon, working well :+1: 
I just add a commit to completely hide the cols in the rendered html

**Comment by jorgheymans** [comment]
👍 👍

Op ma 2 dec. 2019 13:36 schreef Ludovic DEHON <notifications@github.com>:

**Comment by ankon** [comment]
Thanks a lot! Now I just have to spend some time rebasing #134 for further experiments :)

**Pull request merged**
