### PR TITLE
support schema reference in record header for avro deserialization (#231)

### PR DESCRIPTION
**Pull request by tine2k**

### CODE REVIEW

**Comment by tchiotludo** [comment]
Sorry to respond late.

I prefer to merge this one : https://github.com/tchiotludo/kafkahq/pull/228 that start sooner. 
And like I guess, there is some conflict between both work. 
Is it possible to merge the work with current dev ? 
Especially on the `AvroSerializer.java` that is in dev that is the same than your `AvroWireFormatConverter.java ` please ? 

Sorry for that conflict :disappointed:

**Comment by tine2k** [comment]
No worries. Sure, no problem.

**Comment by tine2k** [comment]
Rebased, resolved, and retested. Looks good.

**Comment by tchiotludo** [comment]
nice work ! 
thanks :+1:

**Pull request merged**
